apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: result
  name: result
spec: 
  type: NodePort
  ports:
    - port: 80 
      targetPort: 80
  selector:
    name: result
    app: example-voting-app
    role: resultapp
