apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: vote
  name: vote
spec: 
  type: NodePort
  ports:
    - port: 80 
      targetPort: 80
  selector:
    name: vote
    app: example-voting-app
    role: voteapp
